version: '3.8'

services:
  tg-agent:
    build: .
    container_name: tg-ai-agent
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data     # Для сессии и БД
      - ./config.yaml:/app/config.yaml # Пробрасываем конфиг, чтобы юзер мог менять промпты прямо на сервере