services:
  tg-agent:
    build: .
    container_name: tg-ai-agent
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data          # Для БД и сессии
      - ./config.yaml:/app/config.yaml # Чтобы можно было менять промпты без пересборки
      - ./credentials.json:/app/credentials.json